name: ci
on:
  push:
    branches:
      - master
      - dev

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ~1.20

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Linter
        run: go mod verify

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.20

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Verify dependencies
        run: go mod verify

      - name: Build
        run: make build

  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ~1.20

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Tests
        run: make test
        
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ~1.20

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Integration tests
        run: make integration-test
